-- Production compatibility foundation for Player Profiles.
-- Additive migration: creates the backing mart table and replaces the compat view.
-- Data is populated by src/materialize_player_profiles.py.

CREATE TABLE IF NOT EXISTS `{{PROJECT_ID}}.{{DATASET_ID}}.mart_player_profiles_current` (
    player_id_internal STRING,
    source_player_key STRING,
    sleeper_player_id STRING,
    gsis_id STRING,
    pfr_id STRING,
    espn_id STRING,
    yahoo_id STRING,
    display_name STRING,
    full_name STRING,
    normalized_name STRING,
    position STRING,
    fantasy_positions STRING,
    current_team STRING,
    active_status STRING,
    rookie_year INT64,
    birth_date DATE,
    age FLOAT64,
    as_of_season INT64 NOT NULL,
    as_of_week INT64 NOT NULL,
    scoring_profile_id STRING NOT NULL,
    league_type_id STRING,
    roster_format_id STRING,
    last_seen_season INT64,
    last_seen_week INT64,
    games_played_current_season INT64,
    bye_week INT64,
    fantasy_points_current_season FLOAT64,
    fantasy_points_per_game_current_season FLOAT64,
    fantasy_points_last_3 FLOAT64,
    fantasy_points_last_5 FLOAT64,
    fantasy_points_last_8 FLOAT64,
    total_fantasy_points_standard FLOAT64,
    total_fantasy_points_half_ppr FLOAT64,
    total_fantasy_points_ppr FLOAT64,
    position_rank_by_profile INT64,
    overall_rank_by_profile INT64,
    snaps_last_3 FLOAT64,
    snap_share_last_3 FLOAT64,
    targets_last_3 FLOAT64,
    target_share_last_3 FLOAT64,
    carries_last_3 FLOAT64,
    rush_share_last_3 FLOAT64,
    receptions_last_3 FLOAT64,
    air_yards_last_3 FLOAT64,
    air_yard_share_last_3 FLOAT64,
    red_zone_opportunities_last_3 FLOAT64,
    high_value_touches_last_3 FLOAT64,
    role_summary_json STRING,
    yards_per_carry_current_season FLOAT64,
    yards_per_target_current_season FLOAT64,
    yards_per_reception_current_season FLOAT64,
    catch_rate_current_season FLOAT64,
    td_rate_current_season FLOAT64,
    epa_summary_json STRING,
    efficiency_summary_json STRING,
    model_run_id STRING,
    ranking_version STRING,
    pigskin_rank_overall INT64,
    pigskin_rank_position INT64,
    pigskin_tier STRING,
    pigskin_projection FLOAT64,
    pigskin_confidence FLOAT64,
    pigskin_summary STRING,
    pigskin_movement_json STRING,
    contract_summary_json STRING,
    depth_chart_summary_json STRING,
    college_summary_json STRING,
    rookie_scouting_summary_json STRING,
    prospect_summary_json STRING,
    source_freshness_json STRING,
    missing_data_flags STRING,
    created_at TIMESTAMP NOT NULL,
    refreshed_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(refreshed_at)
CLUSTER BY player_id_internal, position, current_team, scoring_profile_id;

CREATE OR REPLACE VIEW `{{PROJECT_ID}}.{{DATASET_ID}}.compat_player_profiles_current` AS
SELECT *
FROM `{{PROJECT_ID}}.{{DATASET_ID}}.mart_player_profiles_current`;
