-- Ranking backtest feature mart.
-- Additive schema-only migration. No feature rows, backtest rows, champions, or live rankings are inserted.

CREATE TABLE IF NOT EXISTS `{{PROJECT_ID}}.{{DATASET_ID}}.ranking_backtest_feature_mart` (
    source_window_start_season INT64 NOT NULL,
    source_window_end_season INT64 NOT NULL,
    target_season INT64 NOT NULL,
    target_week INT64 NOT NULL,
    scoring_profile_id STRING NOT NULL,
    league_type_id STRING NOT NULL,
    roster_format_id STRING NOT NULL,
    position STRING NOT NULL,
    player_id_internal STRING NOT NULL,
    player_name STRING,
    team STRING,
    source_team STRING,
    recent_points_avg FLOAT64,
    profile_points_score FLOAT64,
    opportunity_score_proxy FLOAT64,
    efficiency_score_proxy FLOAT64,
    analytical_grade_proxy FLOAT64,
    role_stability_score FLOAT64,
    targets FLOAT64,
    carries FLOAT64,
    receiving_yards FLOAT64,
    receiving_epa FLOAT64,
    red_zone_targets FLOAT64,
    success_rate FLOAT64,
    passing_success_rate FLOAT64,
    dropbacks FLOAT64,
    rushing_attempts FLOAT64,
    rush_success_rate FLOAT64,
    receiving_usage FLOAT64,
    cpoe FLOAT64,
    usage_volume FLOAT64,
    epa_per_play FLOAT64,
    passing_epa_per_play FLOAT64,
    team_epa_per_play FLOAT64,
    red_zone_opportunities FLOAT64,
    goal_line_opportunities FLOAT64,
    snap_share_proxy FLOAT64,
    air_yards FLOAT64,
    team_pass_rate FLOAT64,
    points_per_game_slope_3yr FLOAT64,
    total_points_slope_3yr FLOAT64,
    opportunity_slope_3yr FLOAT64,
    target_share_slope_3yr FLOAT64,
    carry_share_slope_3yr FLOAT64,
    receiving_usage_slope_3yr FLOAT64,
    wopr_slope_3yr FLOAT64,
    epa_slope_3yr FLOAT64,
    efficiency_slope_3yr FLOAT64,
    availability_rate_3yr FLOAT64,
    weekly_volatility_3yr FLOAT64,
    improving_3yr FLOAT64,
    declining_3yr FLOAT64,
    breakout_trajectory_3yr FLOAT64,
    target_fantasy_points FLOAT64,
    actual_position_rank INT64,
    actual_overall_rank INT64,
    replacement_points FLOAT64,
    value_over_replacement FLOAT64,
    top_24_overall BOOL,
    top_50_overall BOOL,
    top_100_overall BOOL,
    actual_pick_band STRING,
    predictor_missing_flags_json STRING NOT NULL,
    outcome_missing_flags_json STRING NOT NULL,
    source_freshness_json STRING NOT NULL,
    provenance_json STRING NOT NULL,
    created_at TIMESTAMP NOT NULL
)
PARTITION BY RANGE_BUCKET(target_season, GENERATE_ARRAY(1999, 2050, 1))
CLUSTER BY scoring_profile_id, position, player_id_internal, source_window_end_season;
