-- Phase 32.12: additive opportunity and role metrics for ranking research.
-- No destructive DDL. No live ranking tables are modified.

CREATE TABLE IF NOT EXISTS `{{PROJECT_ID}}.{{DATASET_ID}}.player_week_opportunity_metrics` (
  opportunity_metric_version STRING NOT NULL,
  opportunity_run_id STRING NOT NULL,
  season INT64 NOT NULL,
  week INT64 NOT NULL,
  player_id_internal STRING NOT NULL,
  player_name STRING,
  team STRING,
  opponent_team STRING,
  position STRING NOT NULL,
  targets FLOAT64,
  carries FLOAT64,
  receptions FLOAT64,
  air_yards FLOAT64,
  rushing_yards FLOAT64,
  receiving_yards FLOAT64,
  passing_yards FLOAT64,
  pass_attempts FLOAT64,
  rush_attempts FLOAT64,
  team_plays FLOAT64,
  team_pass_attempts FLOAT64,
  team_rush_attempts FLOAT64,
  team_targets FLOAT64,
  team_air_yards FLOAT64,
  team_epa_per_play FLOAT64,
  team_neutral_pass_rate FLOAT64,
  target_share FLOAT64,
  carry_share FLOAT64,
  opportunity_share FLOAT64,
  air_yards_share FLOAT64,
  weighted_opportunity FLOAT64,
  wopr FLOAT64,
  red_zone_targets FLOAT64,
  red_zone_carries FLOAT64,
  red_zone_touches FLOAT64,
  inside_10_carries FLOAT64,
  inside_5_carries FLOAT64,
  goal_line_carry_share FLOAT64,
  red_zone_opportunity_share FLOAT64,
  high_value_touches FLOAT64,
  high_value_opportunity_score FLOAT64,
  receiving_equity_score FLOAT64,
  qb_rushing_leverage_index FLOAT64,
  wr_dominance_score FLOAT64,
  te_receiving_role_dominance_score FLOAT64,
  team_environment_score FLOAT64,
  spike_week_flag BOOL,
  bust_week_flag BOOL,
  elite_week_flag BOOL,
  source_freshness_json STRING,
  missing_flags_json STRING,
  provenance_json STRING,
  created_at TIMESTAMP NOT NULL
);

ALTER TABLE `{{PROJECT_ID}}.{{DATASET_ID}}.ranking_backtest_feature_mart`
ADD COLUMN IF NOT EXISTS qb_rushing_leverage_index FLOAT64,
ADD COLUMN IF NOT EXISTS rb_high_value_opportunity_score FLOAT64,
ADD COLUMN IF NOT EXISTS receiving_role_dominance_score FLOAT64,
ADD COLUMN IF NOT EXISTS red_zone_usage_score FLOAT64,
ADD COLUMN IF NOT EXISTS goal_line_usage_score FLOAT64,
ADD COLUMN IF NOT EXISTS team_environment_score FLOAT64,
ADD COLUMN IF NOT EXISTS spike_week_rate_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS bust_week_rate_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS elite_week_rate_3yr FLOAT64;
