-- Phase 32.13: additive ffopportunity/xFP ideal stats lane for ranking research.
-- No destructive DDL. No live rankings, champions, or detail backtest rows are modified.

CREATE TABLE IF NOT EXISTS `{{PROJECT_ID}}.{{DATASET_ID}}.raw_ffopportunity_weekly` (
  source_version STRING NOT NULL,
  season INT64 NOT NULL,
  week INT64 NOT NULL,
  game_id STRING,
  source_player_id STRING NOT NULL,
  player_id_internal STRING NOT NULL,
  player_name STRING,
  team STRING,
  position STRING,
  pass_attempt FLOAT64,
  rec_attempt FLOAT64,
  rush_attempt FLOAT64,
  pass_fantasy_points_exp FLOAT64,
  rec_fantasy_points_exp FLOAT64,
  rush_fantasy_points_exp FLOAT64,
  total_fantasy_points_exp FLOAT64,
  pass_fantasy_points FLOAT64,
  rec_fantasy_points FLOAT64,
  rush_fantasy_points FLOAT64,
  total_fantasy_points FLOAT64,
  pass_fantasy_points_diff FLOAT64,
  rec_fantasy_points_diff FLOAT64,
  rush_fantasy_points_diff FLOAT64,
  total_fantasy_points_diff FLOAT64,
  pass_fantasy_points_exp_team FLOAT64,
  rec_fantasy_points_exp_team FLOAT64,
  rush_fantasy_points_exp_team FLOAT64,
  total_fantasy_points_exp_team FLOAT64,
  raw_payload_json STRING,
  source_refresh_id STRING NOT NULL,
  loaded_at TIMESTAMP NOT NULL,
  loaded_by STRING NOT NULL
)
PARTITION BY RANGE_BUCKET(season, GENERATE_ARRAY(1999, 2050, 1))
CLUSTER BY week, player_id_internal, position, source_version;

CREATE TABLE IF NOT EXISTS `{{PROJECT_ID}}.{{DATASET_ID}}.player_week_ideal_opportunity_metrics` (
  source_version STRING NOT NULL,
  ideal_metric_run_id STRING NOT NULL,
  season INT64 NOT NULL,
  week INT64 NOT NULL,
  player_id_internal STRING NOT NULL,
  player_name STRING,
  team STRING,
  position STRING NOT NULL,
  expected_fantasy_points FLOAT64,
  expected_rushing_points FLOAT64,
  expected_receiving_points FLOAT64,
  expected_passing_points FLOAT64,
  fantasy_points FLOAT64,
  fantasy_points_over_expectation FLOAT64,
  xfp_share FLOAT64,
  xfp_score FLOAT64,
  high_value_xfp_score FLOAT64,
  offensive_snap_share FLOAT64,
  snap_count FLOAT64,
  snap_share_trend FLOAT64,
  role_stability_from_snaps FLOAT64,
  target_share FLOAT64,
  air_yards_share FLOAT64,
  wopr FLOAT64,
  receiving_role_dominance_xfp FLOAT64,
  receiving_xfp_per_snap FLOAT64,
  rush_xfp FLOAT64,
  receiving_xfp FLOAT64,
  high_value_touch_xfp FLOAT64,
  goal_line_usage_score FLOAT64,
  red_zone_usage_score FLOAT64,
  qb_ngs_efficiency_score FLOAT64,
  injury_risk_score FLOAT64,
  depth_chart_role_score FLOAT64,
  missing_flags_json STRING NOT NULL,
  source_provenance_json STRING NOT NULL,
  source_updated_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY RANGE_BUCKET(season, GENERATE_ARRAY(1999, 2050, 1))
CLUSTER BY week, player_id_internal, position, source_version;

ALTER TABLE `{{PROJECT_ID}}.{{DATASET_ID}}.ranking_backtest_feature_mart`
ADD COLUMN IF NOT EXISTS xfp_score_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS xfp_share_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS fantasy_points_over_expectation_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS offensive_snap_share_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS snap_role_stability_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS receiving_role_dominance_xfp_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS high_value_xfp_score_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS qb_ngs_efficiency_score_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS injury_risk_score_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS depth_chart_role_score_3yr FLOAT64;
