-- Phase 32.15: additive PBP ffopportunity pass/rush split lane.
-- No destructive DDL. No live rankings, champions, or detail backtest rows are modified.

CREATE TABLE IF NOT EXISTS `{{PROJECT_ID}}.{{DATASET_ID}}.raw_ffopportunity_pbp_pass` (
  source_version STRING NOT NULL,
  season INT64 NOT NULL,
  week INT64 NOT NULL,
  game_id STRING NOT NULL,
  play_id INT64 NOT NULL,
  passer_player_id STRING,
  passer_player_id_internal STRING,
  passer_name STRING,
  passer_position STRING,
  receiver_player_id STRING,
  receiver_player_id_internal STRING,
  receiver_name STRING,
  receiver_position STRING,
  team STRING,
  pass_attempt FLOAT64,
  complete_pass FLOAT64,
  air_yards FLOAT64,
  receiving_yards FLOAT64,
  yards_after_catch FLOAT64,
  pass_touchdown FLOAT64,
  interception FLOAT64,
  first_down_pass FLOAT64,
  two_point_attempt FLOAT64,
  two_point_converted FLOAT64,
  yardline_100 FLOAT64,
  goal_to_go FLOAT64,
  pass_completion_exp FLOAT64,
  yards_after_catch_exp FLOAT64,
  yardline_exp FLOAT64,
  pass_touchdown_exp FLOAT64,
  pass_first_down_exp FLOAT64,
  pass_interception_exp FLOAT64,
  two_point_conv_exp FLOAT64,
  raw_payload_json STRING,
  source_refresh_id STRING NOT NULL,
  loaded_at TIMESTAMP NOT NULL,
  loaded_by STRING NOT NULL
)
PARTITION BY RANGE_BUCKET(season, GENERATE_ARRAY(1999, 2050, 1))
CLUSTER BY week, receiver_player_id_internal, passer_player_id_internal, source_version;

CREATE TABLE IF NOT EXISTS `{{PROJECT_ID}}.{{DATASET_ID}}.raw_ffopportunity_pbp_rush` (
  source_version STRING NOT NULL,
  season INT64 NOT NULL,
  week INT64 NOT NULL,
  game_id STRING NOT NULL,
  play_id INT64 NOT NULL,
  rusher_player_id STRING NOT NULL,
  rusher_player_id_internal STRING NOT NULL,
  rusher_name STRING,
  position STRING,
  team STRING,
  rush_attempt FLOAT64,
  rushing_yards FLOAT64,
  rush_touchdown FLOAT64,
  first_down_rush FLOAT64,
  two_point_attempt FLOAT64,
  two_point_converted FLOAT64,
  yardline_100 FLOAT64,
  goal_to_go FLOAT64,
  rushing_yards_exp FLOAT64,
  rushing_td_exp FLOAT64,
  rushing_fd_exp FLOAT64,
  rush_yards_exp FLOAT64,
  rush_touchdown_exp FLOAT64,
  rush_first_down_exp FLOAT64,
  two_point_conv_exp FLOAT64,
  qb_scramble FLOAT64,
  raw_payload_json STRING,
  source_refresh_id STRING NOT NULL,
  loaded_at TIMESTAMP NOT NULL,
  loaded_by STRING NOT NULL
)
PARTITION BY RANGE_BUCKET(season, GENERATE_ARRAY(1999, 2050, 1))
CLUSTER BY week, rusher_player_id_internal, position, source_version;

CREATE TABLE IF NOT EXISTS `{{PROJECT_ID}}.{{DATASET_ID}}.player_week_pbp_opportunity_metrics` (
  source_version STRING NOT NULL,
  pbp_metric_run_id STRING NOT NULL,
  season INT64 NOT NULL,
  week INT64 NOT NULL,
  player_id_internal STRING NOT NULL,
  player_name STRING,
  team STRING,
  position STRING,
  receiving_xfp_pbp FLOAT64,
  target_xfp FLOAT64,
  air_xfp FLOAT64,
  red_zone_target_xfp FLOAT64,
  goal_line_target_xfp FLOAT64,
  high_value_target_xfp FLOAT64,
  receiving_touchdown_xfp FLOAT64,
  receiving_xfp_share FLOAT64,
  passing_xfp_pbp FLOAT64,
  rushing_xfp_pbp FLOAT64,
  red_zone_rush_xfp FLOAT64,
  goal_line_rush_xfp FLOAT64,
  high_value_rush_xfp FLOAT64,
  rushing_touchdown_xfp FLOAT64,
  rushing_xfp_share FLOAT64,
  high_value_xfp_score FLOAT64,
  red_zone_xfp_score FLOAT64,
  goal_line_xfp_score FLOAT64,
  receiving_vs_rushing_xfp_split FLOAT64,
  opportunity_quality_score FLOAT64,
  missing_flags_json STRING NOT NULL,
  source_provenance_json STRING NOT NULL,
  source_updated_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY RANGE_BUCKET(season, GENERATE_ARRAY(1999, 2050, 1))
CLUSTER BY week, player_id_internal, position, source_version;

ALTER TABLE `{{PROJECT_ID}}.{{DATASET_ID}}.ranking_backtest_feature_mart`
ADD COLUMN IF NOT EXISTS receiving_xfp_pbp_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS rushing_xfp_pbp_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS passing_xfp_pbp_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS red_zone_xfp_score_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS goal_line_xfp_score_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS high_value_target_xfp_score_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS high_value_rush_xfp_score_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS receiving_xfp_share_pbp_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS rushing_xfp_share_pbp_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS opportunity_quality_score_3yr FLOAT64,
ADD COLUMN IF NOT EXISTS pbp_xfp_missing_flags_json STRING;
