-- Phase 33.15: Build player-year advanced metrics warehouse structures.
-- Additive schema-only migration. No destructive DDL.

-- 1. Alter player_week_advanced_metrics to align with the new warehouse specifications
ALTER TABLE `{{PROJECT_ID}}.{{DATASET_ID}}.player_week_advanced_metrics`
ADD COLUMN IF NOT EXISTS season_type STRING,
ADD COLUMN IF NOT EXISTS generated_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS gsis_id STRING,
ADD COLUMN IF NOT EXISTS position_group STRING,
ADD COLUMN IF NOT EXISTS source_coverage_json STRING,
ADD COLUMN IF NOT EXISTS missing_flags_json STRING,
ADD COLUMN IF NOT EXISTS proxy_flags_json STRING,
ADD COLUMN IF NOT EXISTS blocked_flags_json STRING,
ADD COLUMN IF NOT EXISTS games INT64,
ADD COLUMN IF NOT EXISTS receptions FLOAT64,
ADD COLUMN IF NOT EXISTS attempts FLOAT64,
ADD COLUMN IF NOT EXISTS dropbacks FLOAT64,
ADD COLUMN IF NOT EXISTS routes_run FLOAT64,
ADD COLUMN IF NOT EXISTS pass_play_snaps FLOAT64,
ADD COLUMN IF NOT EXISTS offensive_snaps FLOAT64,
ADD COLUMN IF NOT EXISTS receiving_yards FLOAT64,
ADD COLUMN IF NOT EXISTS receiving_air_yards FLOAT64,
ADD COLUMN IF NOT EXISTS receiving_yards_after_catch FLOAT64,
ADD COLUMN IF NOT EXISTS receiving_epa FLOAT64,
ADD COLUMN IF NOT EXISTS receiving_epa_per_target FLOAT64,
ADD COLUMN IF NOT EXISTS receiving_first_downs FLOAT64,
ADD COLUMN IF NOT EXISTS receiving_first_down_rate FLOAT64,
ADD COLUMN IF NOT EXISTS goal_line_targets FLOAT64,
ADD COLUMN IF NOT EXISTS end_zone_targets FLOAT64,
ADD COLUMN IF NOT EXISTS yprr FLOAT64,
ADD COLUMN IF NOT EXISTS tprr FLOAT64,
ADD COLUMN IF NOT EXISTS receiving_first_downs_per_route FLOAT64,
ADD COLUMN IF NOT EXISTS route_participation_rate FLOAT64,
ADD COLUMN IF NOT EXISTS rushing_yards FLOAT64,
ADD COLUMN IF NOT EXISTS rushing_epa FLOAT64,
ADD COLUMN IF NOT EXISTS rushing_epa_per_carry FLOAT64,
ADD COLUMN IF NOT EXISTS rushing_first_downs FLOAT64,
ADD COLUMN IF NOT EXISTS rushing_first_down_rate FLOAT64,
ADD COLUMN IF NOT EXISTS red_zone_opportunities FLOAT64,
ADD COLUMN IF NOT EXISTS goal_line_opportunities FLOAT64,
ADD COLUMN IF NOT EXISTS weighted_opportunity_standard FLOAT64,
ADD COLUMN IF NOT EXISTS weighted_opportunity_half_ppr FLOAT64,
ADD COLUMN IF NOT EXISTS weighted_opportunity_ppr FLOAT64,
ADD COLUMN IF NOT EXISTS weighted_opportunity_gng_keeper FLOAT64,
ADD COLUMN IF NOT EXISTS passing_yards FLOAT64,
ADD COLUMN IF NOT EXISTS passing_epa FLOAT64,
ADD COLUMN IF NOT EXISTS passing_epa_per_attempt FLOAT64,
ADD COLUMN IF NOT EXISTS passing_epa_per_dropback FLOAT64,
ADD COLUMN IF NOT EXISTS passing_cpoe FLOAT64,
ADD COLUMN IF NOT EXISTS dakota FLOAT64,
ADD COLUMN IF NOT EXISTS passing_first_downs FLOAT64,
ADD COLUMN IF NOT EXISTS passing_first_down_rate FLOAT64,
ADD COLUMN IF NOT EXISTS qb_rushing_baseline_score FLOAT64,
ADD COLUMN IF NOT EXISTS ngs_avg_separation FLOAT64,
ADD COLUMN IF NOT EXISTS ngs_avg_cushion FLOAT64,
ADD COLUMN IF NOT EXISTS ngs_yac_above_expectation FLOAT64,
ADD COLUMN IF NOT EXISTS ngs_rushing_efficiency FLOAT64,
ADD COLUMN IF NOT EXISTS ngs_rush_yards_over_expected FLOAT64,
ADD COLUMN IF NOT EXISTS ngs_rush_yards_over_expected_per_att FLOAT64,
ADD COLUMN IF NOT EXISTS ngs_box_count_rate FLOAT64,
ADD COLUMN IF NOT EXISTS ngs_qb_time_to_throw FLOAT64,
ADD COLUMN IF NOT EXISTS ngs_qb_aggressiveness FLOAT64,
ADD COLUMN IF NOT EXISTS ngs_qb_cpoe FLOAT64,
ADD COLUMN IF NOT EXISTS offensive_snap_share FLOAT64,
ADD COLUMN IF NOT EXISTS snap_role_stability FLOAT64,
ADD COLUMN IF NOT EXISTS availability_score FLOAT64,
ADD COLUMN IF NOT EXISTS injury_status_score FLOAT64,
ADD COLUMN IF NOT EXISTS injury_burden_score FLOAT64,
ADD COLUMN IF NOT EXISTS missed_time_risk_score FLOAT64,
ADD COLUMN IF NOT EXISTS route_metrics_source_status STRING,
ADD COLUMN IF NOT EXISTS ngs_source_status STRING,
ADD COLUMN IF NOT EXISTS participation_source_status STRING,
ADD COLUMN IF NOT EXISTS contract_source_status STRING,
ADD COLUMN IF NOT EXISTS pressure_coverage_source_status STRING;

-- 2. Create player_season_advanced_metrics table
CREATE TABLE IF NOT EXISTS `{{PROJECT_ID}}.{{DATASET_ID}}.player_season_advanced_metrics` (
    metric_version STRING NOT NULL,
    generated_at TIMESTAMP NOT NULL,
    season INT64 NOT NULL,
    season_type STRING NOT NULL,
    player_id_internal STRING NOT NULL,
    gsis_id STRING,
    player_name STRING,
    position STRING NOT NULL,
    position_group STRING,
    team STRING,
    teams_json STRING,
    source_coverage_json STRING,
    missing_flags_json STRING,
    proxy_flags_json STRING,
    blocked_flags_json STRING,
    games INT64,
    targets FLOAT64,
    receptions FLOAT64,
    carries FLOAT64,
    attempts FLOAT64,
    dropbacks FLOAT64,
    routes_run FLOAT64,
    pass_play_snaps FLOAT64,
    offensive_snaps FLOAT64,
    receiving_yards FLOAT64,
    receiving_air_yards FLOAT64,
    receiving_yards_after_catch FLOAT64,
    receiving_epa FLOAT64,
    receiving_epa_per_target FLOAT64,
    receiving_first_downs FLOAT64,
    receiving_first_down_rate FLOAT64,
    target_share FLOAT64,
    air_yards_share FLOAT64,
    wopr FLOAT64,
    racr FLOAT64,
    adot FLOAT64,
    red_zone_targets FLOAT64,
    goal_line_targets FLOAT64,
    end_zone_targets FLOAT64,
    yprr FLOAT64,
    tprr FLOAT64,
    receiving_first_downs_per_route FLOAT64,
    route_participation_rate FLOAT64,
    rushing_yards FLOAT64,
    rushing_epa FLOAT64,
    rushing_epa_per_carry FLOAT64,
    rushing_first_downs FLOAT64,
    rushing_first_down_rate FLOAT64,
    red_zone_carries FLOAT64,
    goal_line_carries FLOAT64,
    red_zone_opportunities FLOAT64,
    goal_line_opportunities FLOAT64,
    weighted_opportunity_standard FLOAT64,
    weighted_opportunity_half_ppr FLOAT64,
    weighted_opportunity_ppr FLOAT64,
    weighted_opportunity_gng_keeper FLOAT64,
    passing_yards FLOAT64,
    passing_epa FLOAT64,
    passing_epa_per_attempt FLOAT64,
    passing_epa_per_dropback FLOAT64,
    passing_cpoe FLOAT64,
    dakota FLOAT64,
    passing_first_downs FLOAT64,
    passing_first_down_rate FLOAT64,
    qb_rushing_baseline_score FLOAT64,
    ngs_avg_separation FLOAT64,
    ngs_avg_cushion FLOAT64,
    ngs_yac_above_expectation FLOAT64,
    ngs_rushing_efficiency FLOAT64,
    ngs_rush_yards_over_expected FLOAT64,
    ngs_rush_yards_over_expected_per_att FLOAT64,
    ngs_box_count_rate FLOAT64,
    ngs_qb_time_to_throw FLOAT64,
    ngs_qb_aggressiveness FLOAT64,
    ngs_qb_cpoe FLOAT64,
    offensive_snap_share FLOAT64,
    snap_role_stability FLOAT64,
    availability_score FLOAT64,
    injury_status_score FLOAT64,
    injury_burden_score FLOAT64,
    missed_time_risk_score FLOAT64,
    route_metrics_source_status STRING,
    ngs_source_status STRING,
    participation_source_status STRING,
    contract_source_status STRING,
    pressure_coverage_source_status STRING
)
PARTITION BY RANGE_BUCKET(season, GENERATE_ARRAY(1999, 2050, 1))
CLUSTER BY position, player_id_internal;

-- 3. Create player_metric_source_coverage table
CREATE TABLE IF NOT EXISTS `{{PROJECT_ID}}.{{DATASET_ID}}.player_metric_source_coverage` (
    metric_version STRING NOT NULL,
    season INT64 NOT NULL,
    metric_name STRING NOT NULL,
    source_status STRING NOT NULL,
    coverage_count INT64,
    non_null_count INT64,
    created_at TIMESTAMP NOT NULL
)
PARTITION BY RANGE_BUCKET(season, GENERATE_ARRAY(1999, 2050, 1))
CLUSTER BY metric_name;
